---
title: "weeklyForecast"
output: 
  #rmarkdown::github_document
  html_document:
    toc: true
    number_sections: true
    keep_md: true
---



```{r setup, include=F}
knitr::opts_chunk$set(echo = TRUE)

library(ggplot2)
library(tidyverse)
library(nlme)
library(magrittr)


rm(list = ls())
```





# Mar-Aug
```{r}
weeklyCases <- read.csv('https://raw.githubusercontent.com/kentranz/socialMobilityCOVID/master/data/weeklyCases.csv')

cutOff <- as.Date("2020-08-31")

testRange <- 2
```


## LME
```{r}

modelName = 'lmeAug_' 

train <- weeklyCases %>% 
  filter(weekNum > 3 & as.Date(date) < cutOff)


model <- lme(fixed = case.rate ~ casesTminus1.rate + casesTminus2.rate,
    random = ~ casesTminus1.rate + casesTminus2.rate - 1 | city,
    data = train
    )
summary(model)

# test to hold all date data points up to testRange
test <- weeklyCases %>% 
  filter(weekNum > 3 
       & as.Date(date) > cutOff
       & as.Date(date) <= (cutOff + testRange*7)
       ) 


# Predict one new observation at a time
# For each new test, refit the model with actual observed Y
for (i in 1:testRange)
{
  
  if(i > 1)
  {
    train <- weeklyCases %>% 
      filter(weekNum > 3 & as.Date(date) <= (cutOff - 1*7 + i*7))

    model <- update(model, data = train)
  }
  
  # test to check correct training window
  # print(i)
  # print(max(as.Date(train$date)))
  
  # filter test set to calculate pred for only 1 day at a time
  tempTest <- test %>% filter(weekNum > 3 
       & as.Date(date) >= (cutOff + (i-1)*7)
       & as.Date(date) <= (cutOff + i*7)
       ) 
  tempTest$pred <- predict(model, newdata = tempTest)
  
  # test to check for correct test window
  # print(max(as.Date(tempTest$date)))
  
  # create design matrix
  # [-2] drops response from formula
  Designmat <- model.matrix(formula(model)[-2], tempTest)
  
  # compute XVX′ to get the variance-covariance matrix of the predictions
  # extract the diagonal of this matrix to get variances of predictions
  predvar <- diag(Designmat %*% vcov(model) %*% t(Designmat)) 
  #results7$SE <- sqrt(predvar) 
  tempTest$SE <- sqrt(predvar + model$sigma^2) # sigma is the estimated within-group error standard deviation
  tempTest$lowerCI <- tempTest$pred - 1.96*tempTest$SE
  tempTest$upperCI <- tempTest$pred + 1.96*tempTest$SE
  
  test %<>%
    left_join(tempTest %>% select(city, date, pred, lowerCI, upperCI)
              , by = c("date" = "date", "city" = "city"))
   
  if(i > 1)
  {
    test %<>% 
      mutate(pred = coalesce(pred.x, pred.y)
             , lowerCI = coalesce(lowerCI.x, lowerCI.y)
             , upperCI = coalesce(upperCI.x, upperCI.y)
             ) %>%
      select(-pred.x, -pred.y
             , -lowerCI.x, -lowerCI.y
             , -upperCI.x, -upperCI.y)
  }
}



# pull all metrics into one dataframe called dailyMetrics
metrics <- test %>% 
    group_by(city) %>%
    summarize(MAE = round(mean(abs(case.rate - pred)) , 2)
              , MAPE = round(mean(abs(case.rate - pred)/case.rate) , 2)
              , CP = round(sum(case.rate >= lowerCI & case.rate <= upperCI ) / n() , 2)
              ) %>%
    left_join( test %>%
                 group_by(city) %>%
                 summarize(MAE = round(mean(abs(case.rate - pred)) , 2)
                           , MAPE = round(mean(abs(case.rate - pred)/case.rate) , 2)
                           , CP = round(sum(case.rate >= lowerCI & case.rate <= upperCI ) / n() , 2)
                           )
               , by = "city"
               , suffix = c("_1w", "_2w")
               ) %>%
    rename_at(vars(-city), ~ paste0(modelName,.)) %>%
    arrange(as.character(city))

dailyMetrics <- metrics

```